- name: playbook docker compose
  hosts: all
  become: yes
  tasks:

  - name: copy docker-compose.yml
    copy:
      src: app/docker-compose.yml
      dest: /tmp/
    
  - name: test docker-compose
    docker_compose:
      project_src: /tmp/
      state: present

