- name:  Playbook nginx
  hosts: all
  become: yes
  vars: 
   nginx_port: 8888
  tasks:
  - name: install nginx
    apt:
      name: nginx,curl
      state: present
      cache_valid_time: 3600
      update_cache: yes

  - name: remove default file
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-enabled/default"



  - name: installation du vhost
    template: 
      src: vhost.conf.j2
      dest: "/etc/nginx/sites-available/vhost.conf"
      owner: root
      group: root
      mode: 0644


  - name: activate vhost
    file:
      src: /etc/nginx/sites-available/vhost.conf
      dest: /etc/nginx/sites-enabled/vhost.conf
      state: link

  - name: start nginx
    systemd:
      name: nginx
      state: started


