- name: playbook image
  hosts: all
  become: yes
  tasks:


  - name: copy image
    copy: 
      src: image.test.v1.0.tar
      dest: /tmp/

  - name: Pull an image
    docker_image:
      name: archive
      tag: v1.0
      load_path: /tmp/image.test.v1.0.tar
      source: load

