- name: test du module dokcer_image
  hosts: all
  become: yes
  tasks:

  - name: install docker, docker for python et docker-compose
    apt: 
      name: docker.io, python3-docker, docker-compose
      state: present 
      update_cache: yes
      cache_valid_time: 3600

  - name: start docker
    systemd:
       name: docker
       state: started
       enabled: yes 
  - name: copy docker-compose.yml
    copy:
      src: app/docker-compose.yml
      dest: /tmp/

  - name: test docker-compose
    docker_compose:
      project_src: /tmp/
      state: absent
